# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Auto-DevOps.gitlab-ci.yml
stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
before_script:
- echo "Running common setup steps for all jobs"
build:
  stage: build
  script:
  - echo "Building project for branch $CI_COMMIT_REF_NAME"
  rules:
  - if: "$CI_COMMIT_REF_NAME"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
test:
  stage: test
  script:
  - echo "Running tests for branch $CI_COMMIT_REF_NAME"
  - echo "Running SAST scan..."
  rules:
  - if: "$CI_COMMIT_REF_NAME"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
deploy:
  stage: deploy
  script:
  - echo "Deploying project for branch $CI_COMMIT_REF_NAME"
  rules:
  - if: "$CI_COMMIT_REF_NAME"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
after_script:
- echo "Running cleanup tasks"
sast:
  stage: test
