# Include GitLab's pre-built SAST scanning template
include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

# Global setup (this runs before each job)
before_script:
  - echo "Running common setup steps for all jobs"

# Build Job (runs for all branches and PRs)
build:
  stage: build
  script:
    - echo "Building project for branch $CI_COMMIT_REF_NAME"
  rules:
    - if: '$CI_COMMIT_REF_NAME' # Run for all branches
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run for merge requests

# Test Job (runs for all branches and PRs)
test:
  stage: test
  script:
    - echo "Running tests for branch $CI_COMMIT_REF_NAME"
  rules:
    - if: '$CI_COMMIT_REF_NAME' # Run for all branches
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run for merge requests

# Deploy Job (runs for all branches and PRs)
deploy:
  stage: deploy
  script:
    - echo "Deploying project for branch $CI_COMMIT_REF_NAME"
  rules:
    - if: '$CI_COMMIT_REF_NAME' # Run for all branches
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run for merge requests

# Optional: Cleanup after all jobs are complete
after_script:
  - echo "Running cleanup tasks"
