name: Trigger GitLab CI on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR open, synchronize (commit push), and reopen events

jobs:
  trigger-gitlab-ci:
    name: Trigger GitLab CI job
    runs-on: ubuntu-latest

    steps:
      # Optional: Checkout code if GitLab needs to access it, you can skip this if not needed
      - name: Checkout code
        uses: actions/checkout@v2  # You can skip this step if GitLab does not require the code from GitHub

      - name: Trigger GitLab CI Job
        uses: appleboy/gitlab-ci-action@0.0.1
        with:
          host: ${{ secrets.GITLAB_HOST }}  # GitLab instance URL (e.g., https://gitlab.com for GitLab's cloud service)
          token: ${{ secrets.GITLAB_TOKEN }}  # GitLab Personal Access Token (with api scope)
          project_id: ${{ secrets.GITLAB_PROJECT_ID }}  # GitLab project ID (numeric ID of your GitLab repository)
          ref: ${{ github.head_ref }}  # The branch or commit ref that triggered the PR (usually the branch name)
          trigger_token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}  # Optional: GitLab CI/CD Trigger Token (if required)
