name: Trigger GitLab CI on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR open, synchronize (commit push), and reopen events

jobs:
  trigger-gitlab-ci:
    name: Trigger GitLab CI Job
    runs-on: ubuntu-latest

    steps:
      # Optional: Checkout code if GitLab needs to access it
      - name: Checkout code
        uses: actions/checkout@v2  # Ensure the code is available if needed by GitLab pipeline

      # Trigger GitLab CI Job using the GitHub Marketplace Action
      - name: Trigger GitLab CI Job
        uses: appleboy/gitlab-ci-action@v1.3.0
        with:
          entryPoint: |
            curl --request POST --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
              --form "ref=${{ github.head_ref }}" \
              "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline"
          args: |
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" # Optional: GitLab Personal Access Token (with api scope)
