name: Trigger Gitlab Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Gitlab Pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITLAB_URL: https://gitlab.com
        run: |
          # Get branch name from pull request
          BRANCH_NAME=${{ github.head_ref }}

          # Trigger Gitlab Pipeline
          curl --request POST "${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/trigger/pipeline" \
            --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
            --form "ref=${BRANCH_NAME}" \
            --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}"
