name: Trigger GitLab Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITLAB_URL: https://gitlab.com
        run: |
          # Use a default branch if no branch is specified
          DEFAULT_BRANCH="main"  # Change this to your default branch
          
          # Trigger GitLab Pipeline
          curl --request POST \
               --form token="${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
               --form ref="${DEFAULT_BRANCH}" \
               "${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/trigger/pipeline"
